import type { StudySpace } from "./types";

export const initialSpaces: StudySpace[] = [
  // ─── NYU Manhattan (Washington Square) ──────────────────────────

  // Bobst Library – multiple floors (coords spread for pin visibility)
  {
    id: "bobst-ll2",
    name: "Bobst Library – LL2 Computer Lab",
    building: "Bobst Library",
    address: "70 Washington Sq S",
    floor: "Lower Level 2",
    latitude: 40.72935,
    longitude: -73.99710,
    noise: "quiet",
    type: "library",
    amenities: ["Power Outlets", "Wi-Fi", "Computers", "Printers"],
    hours: "7 AM – 1 AM",
    capacity: "~80 seats",
    checkins: 12,
    tip: "Gets packed during midterms. Come before 10 AM for guaranteed seating.",
    favorite: false,
    bookingUrl: "https://nyu.libcal.com/spaces?lid=2120",
  },
  {
    id: "bobst-4",
    name: "Bobst Library – 4th Floor",
    building: "Bobst Library",
    address: "70 Washington Sq S",
    floor: "4th Floor",
    latitude: 40.72960,
    longitude: -73.99750,
    noise: "quiet",
    type: "library",
    amenities: ["Power Outlets", "Wi-Fi", "Natural Light"],
    hours: "7 AM – 1 AM",
    capacity: "~120 seats",
    checkins: 8,
    tip: "The window seats overlooking Washington Square are prime real estate.",
    favorite: false,
  },
  {
    id: "bobst-10",
    name: "Bobst Library – 10th Floor",
    building: "Bobst Library",
    address: "70 Washington Sq S",
    floor: "10th Floor",
    latitude: 40.72985,
    longitude: -73.99785,
    noise: "silent",
    type: "library",
    amenities: ["Power Outlets", "Wi-Fi"],
    hours: "7 AM – 1 AM",
    capacity: "~40 seats",
    checkins: 3,
    tip: "Absolute silence enforced. Don't even unzip your bag too loudly.",
    favorite: false,
  },
  {
    id: "bobst-pods",
    name: "Bobst Library – Study Pods",
    building: "Bobst Library",
    address: "70 Washington Sq S",
    floor: "Various Floors",
    latitude: 40.72945,
    longitude: -73.99790,
    noise: "silent",
    type: "study_room",
    amenities: ["Enclosed", "Wi-Fi", "Bookable"],
    hours: "7 AM – 1 AM",
    capacity: "2-4 per pod",
    checkins: 0,
    tip: "Book via NYU Libraries site. Fills up fast — book 2-3 days in advance.",
    favorite: false,
    bookingUrl: "https://nyu.libcal.com/spaces?lid=2120",
  },

  // Kimmel Center
  {
    id: "kimmel-4",
    name: "Kimmel Center – 4th Floor Lounge",
    building: "Kimmel Center",
    address: "60 Washington Sq S",
    floor: "4th Floor",
    latitude: 40.72990,
    longitude: -73.99830,
    noise: "moderate",
    type: "lounge",
    amenities: ["Power Outlets", "Wi-Fi", "Food Nearby", "Couches"],
    hours: "7 AM – 11 PM",
    capacity: "~60 seats",
    checkins: 15,
    tip: "Great for casual group work. Starbucks is right downstairs.",
    favorite: false,
  },
  {
    id: "kimmel-commuter",
    name: "Kimmel Commuter Lounge",
    building: "Kimmel Center",
    address: "60 Washington Sq S",
    floor: "3rd Floor",
    latitude: 40.72970,
    longitude: -73.99860,
    noise: "moderate",
    type: "lounge",
    amenities: ["Microwaves", "Lockers", "Wi-Fi", "Power Outlets"],
    hours: "8 AM – 10 PM",
    capacity: "~30 seats",
    checkins: 5,
    tip: "Underused gem if you're a commuter. Has lockers you can use all day.",
    favorite: false,
  },

  // LaGuardia STC
  {
    id: "laguardia-stc",
    name: "LaGuardia Student Tech Center",
    building: "LaGuardia Co-op",
    address: "541 LaGuardia Place",
    floor: "Multiple Floors",
    latitude: 40.72845,
    longitude: -73.99890,
    noise: "quiet",
    type: "lab",
    amenities: ["Computers", "Printers", "AV Booths", "Wi-Fi", "Gaming/VR"],
    hours: "Check NYU site",
    capacity: "~50 seats",
    checkins: 6,
    tip: "The AV booths are perfect for recording presentations or Zoom calls.",
    favorite: false,
  },

  // Third North STC
  {
    id: "third-north-stc",
    name: "Third North Tech Center",
    building: "Third North Residence",
    address: "75 Third Avenue",
    floor: "C3 Level (Sub-basement)",
    latitude: 40.73200,
    longitude: -73.98920,
    noise: "quiet",
    type: "lab",
    amenities: ["Computers", "Printers", "Wi-Fi", "Study Rooms"],
    hours: "Mon-Fri 10 AM – 7 PM, Sat-Sun 11 AM – 7 PM",
    capacity: "~25 seats",
    checkins: 2,
    tip: "Most people forget this exists. Rarely crowded even during finals.",
    favorite: false,
  },

  // Warren Weaver Hall (Courant)
  {
    id: "courant-lounge",
    name: "Courant Lounge",
    building: "Warren Weaver Hall",
    address: "251 Mercer Street",
    floor: "13th Floor",
    latitude: 40.72880,
    longitude: -73.99560,
    noise: "quiet",
    type: "lounge",
    amenities: ["Wi-Fi", "Power Outlets", "Whiteboards", "Coffee Machine"],
    hours: "8 AM – 10 PM",
    capacity: "~25 seats",
    checkins: 4,
    tip: "CS and Math students hang out here. Great views and usually has coffee.",
    favorite: false,
  },

  // Silver Center
  {
    id: "silver-2",
    name: "Silver Center – 2nd Floor Atrium",
    building: "Silver Center",
    address: "100 Washington Sq E",
    floor: "2nd Floor",
    latitude: 40.73015,
    longitude: -73.99710,
    noise: "moderate",
    type: "lounge",
    amenities: ["Wi-Fi", "Power Outlets", "Natural Light"],
    hours: "8 AM – 10 PM",
    capacity: "~35 seats",
    checkins: 7,
    tip: "Open tables between classes. Gets noisy during class changeover.",
    favorite: false,
  },

  // GCASL
  {
    id: "gcasl-6",
    name: "GCASL – 6th Floor Empty Classrooms",
    building: "Global Center for Academic & Spiritual Life",
    address: "238 Thompson Street",
    floor: "6th Floor",
    latitude: 40.72915,
    longitude: -73.99890,
    noise: "silent",
    type: "hidden_gem",
    amenities: ["Whiteboards", "Wi-Fi", "Projector"],
    hours: "When no classes scheduled",
    capacity: "~30 seats",
    checkins: 1,
    tip: "Check Albert for room schedules. Empty classrooms after 6 PM are gold.",
    submittedBy: "Anonymous NYU student",
    favorite: false,
  },

  // Washington Square Park
  {
    id: "wsp",
    name: "Washington Square Park – North Benches",
    building: "Outdoor",
    address: "Washington Square Park",
    floor: "—",
    latitude: 40.73105,
    longitude: -73.99730,
    noise: "loud",
    type: "outdoor",
    amenities: ["Fresh Air", "People Watching"],
    hours: "6 AM – 1 AM",
    capacity: "Plenty",
    checkins: 20,
    tip: "Not for deep focus. Great for light reading or a brainstorm session.",
    favorite: false,
  },

  // Tisch Hall area
  {
    id: "tisch-courtyard",
    name: "Tisch Hall Courtyard",
    building: "Tisch Hall",
    address: "40 W 4th Street",
    floor: "Ground Level",
    latitude: 40.72910,
    longitude: -73.99670,
    noise: "moderate",
    type: "outdoor",
    amenities: ["Fresh Air", "Shaded Seating"],
    hours: "Building hours",
    capacity: "~15 seats",
    checkins: 3,
    tip: "Nice quiet outdoor corner that most non-Stern students don't know about.",
    submittedBy: "Stern junior",
    favorite: false,
  },

  // ─── NYU Tandon (Brooklyn) ──────────────────────────────────────

  // Dibner Library
  {
    id: "dibner-3",
    name: "Dibner Library – Group Study Rooms",
    building: "Bern Dibner Library",
    address: "5 MetroTech Center",
    floor: "3rd Floor",
    latitude: 40.69340,
    longitude: -73.98680,
    noise: "quiet",
    type: "study_room",
    amenities: ["Power Outlets", "Wi-Fi", "Printers", "Bookable"],
    hours: "8 AM – 11 PM",
    capacity: "~50 seats",
    checkins: 9,
    tip: "Tandon's main library floor. Right side tables have the most outlets.",
    favorite: false,
    bookingUrl: "https://nyu.libcal.com/reserve/dibner-group-study",
  },
  {
    id: "dibner-5",
    name: "Dibner Library – Large Group Study",
    building: "Bern Dibner Library",
    address: "5 MetroTech Center",
    floor: "5th Floor",
    latitude: 40.69360,
    longitude: -73.98720,
    noise: "silent",
    type: "study_room",
    amenities: ["Power Outlets", "Wi-Fi", "Bookable", "Whiteboards"],
    hours: "8 AM – 11 PM",
    capacity: "8-12 per room",
    checkins: 4,
    tip: "Larger rooms for team meetings. Book ahead — these go fast.",
    favorite: false,
    bookingUrl: "https://nyu.libcal.com/reserve/dibner-large-group-study",
  },

  // Paulson Center (370 Jay)
  {
    id: "paulson-atrium",
    name: "Paulson Center – Open Atrium",
    building: "Paulson Center",
    address: "370 Jay Street",
    floor: "Ground Floor",
    latitude: 40.69240,
    longitude: -73.98740,
    noise: "moderate",
    type: "lounge",
    amenities: ["Natural Light", "Power Outlets", "Zoom-Friendly", "Wi-Fi"],
    hours: "8 AM – 10 PM",
    capacity: "~30 seats",
    checkins: 11,
    tip: "Huge windows, great natural light. The bean bags are first-come-first-serve.",
    favorite: false,
  },
  {
    id: "paulson-study-rooms",
    name: "Paulson Center – Study Rooms",
    building: "Paulson Center",
    address: "370 Jay Street",
    floor: "2nd Floor",
    latitude: 40.69260,
    longitude: -73.98710,
    noise: "quiet",
    type: "study_room",
    amenities: ["Whiteboards", "Monitor Hookups", "Enclosed", "Wi-Fi", "Bookable"],
    hours: "8 AM – 10 PM",
    capacity: "4-6 per room",
    checkins: 2,
    tip: "Bookable via EMS. Great for group projects — monitors and whiteboards included.",
    favorite: false,
    bookingUrl: "https://ems.nyu.edu/EmsWebApp/",
  },

  // MakerSpace
  {
    id: "makerspace-lounge",
    name: "Tandon MakerSpace Lounge",
    building: "Rogers Hall",
    address: "6 MetroTech Center",
    floor: "1st Floor",
    latitude: 40.69405,
    longitude: -73.98620,
    noise: "moderate",
    type: "lounge",
    amenities: ["Whiteboards", "Wi-Fi", "Power Outlets", "3D Printers Nearby"],
    hours: "9 AM – 9 PM",
    capacity: "~20 seats",
    checkins: 6,
    tip: "Chill vibes. Good for group brainstorming — MakerSpace staff are helpful too.",
    favorite: false,
  },

  // Hidden gem – Jacobs Building
  {
    id: "jacobs-basement",
    name: "Jacobs Building – Basement Tables",
    building: "Jacobs Academic Building",
    address: "2 MetroTech Center",
    floor: "Basement Level",
    latitude: 40.69380,
    longitude: -73.98580,
    noise: "quiet",
    type: "hidden_gem",
    amenities: ["Power Outlets", "Wi-Fi", "Vending Machines"],
    hours: "7 AM – 11 PM",
    capacity: "~15 seats",
    checkins: 1,
    tip: "Barely anyone comes down here. Feels like your own private study hall.",
    submittedBy: "ECE sophomore",
    favorite: false,
  },
];
