import type { Printer } from "./types";

// Real NYU print station locations parsed from the official NYU Print Service
// Google My Maps (mid=1zTCPVJ7EMLZyL-T_bPFOTm24K_7LMbU).
// Coordinates are lng/lat from the KML export, converted to lat/lng here.
// Status seeded as "unknown" — crowd reports will update them at runtime.

const now = new Date();
function hoursAgo(h: number) {
  return new Date(now.getTime() - h * 3_600_000).toISOString();
}

export const initialPrinters: Printer[] = [
  {
    id: "kimmel",
    name: "Kimmel Center for University Life",
    building: "60 Washington Sq S",
    floor: "2nd Floor Mezzanine",
    printer_type: "Color Laser",
    latitude: 40.7299366,
    longitude: -73.9978275,
    status: "working",
    last_updated: hoursAgo(2),
    last_reported_by: "student",
  },
  {
    id: "19w4th",
    name: "19 W 4th St",
    building: "19 W 4th Street",
    floor: "First Floor Lobby",
    printer_type: "B&W Laser",
    latitude: 40.7291036,
    longitude: -73.9951974,
    status: "unknown",
    last_updated: hoursAgo(80),
  },
  {
    id: "laguardia-stc",
    name: "LaGuardia Student Technology Center",
    building: "541 LaGuardia Pl",
    floor: "Main Floor",
    printer_type: "Color Laser",
    latitude: 40.7284682,
    longitude: -73.998016,
    status: "working",
    last_updated: hoursAgo(1),
    last_reported_by: "student",
  },
  {
    id: "third-north",
    name: "Third Avenue North Residence Hall",
    building: "Third Avenue North",
    floor: "C3 Level (sub-basement)",
    printer_type: "Color Laser",
    latitude: 40.7314641,
    longitude: -73.9882166,
    status: "not_working",
    last_updated: hoursAgo(5),
    last_reported_by: "student",
  },
  {
    id: "bobst",
    name: "Elmer Holmes Bobst Library",
    building: "70 Washington Sq S",
    floor: "Lower Level 2 (LL2)",
    printer_type: "Color Laser",
    latitude: 40.7294279,
    longitude: -73.9972212,
    status: "working",
    last_updated: hoursAgo(3),
    last_reported_by: "admin",
  },
  {
    id: "433-1st",
    name: "433 1st Ave",
    building: "433 1st Avenue",
    floor: "Lobby",
    printer_type: "B&W Laser",
    latitude: 40.7387155,
    longitude: -73.9777228,
    status: "unknown",
    last_updated: hoursAgo(96),
  },
  {
    id: "clark-st",
    name: "Clark Street Residence Hall",
    building: "Clark Street Residence",
    floor: "4th Floor",
    printer_type: "B&W Laser",
    latitude: 40.6978152,
    longitude: -73.9939694,
    status: "unknown",
    last_updated: hoursAgo(120),
  },
  {
    id: "80-lafayette",
    name: "80 Lafayette St",
    building: "80 Lafayette Street",
    floor: "Lobby",
    printer_type: "B&W Laser",
    latitude: 40.7171425,
    longitude: -74.0021452,
    status: "unknown",
    last_updated: hoursAgo(72),
  },
  {
    id: "alumni-hall",
    name: "Alumni Hall",
    building: "Alumni Hall",
    floor: "1st Floor Lounge",
    printer_type: "B&W Laser",
    latitude: 40.7302968,
    longitude: -73.9889945,
    status: "working",
    last_updated: hoursAgo(4),
    last_reported_by: "student",
  },
  {
    id: "brittany",
    name: "Brittany Residence Hall",
    building: "Brittany Hall",
    floor: "Lobby",
    printer_type: "B&W Laser",
    latitude: 40.7320519,
    longitude: -73.9918003,
    status: "unknown",
    last_updated: hoursAgo(60),
  },
  {
    id: "bronfman",
    name: "NYU Bronfman Center",
    building: "Bronfman Center for Jewish Student Life",
    floor: "3rd Floor Lounge",
    printer_type: "B&W Laser",
    latitude: 40.7332774,
    longitude: -73.9946311,
    status: "unknown",
    last_updated: hoursAgo(48),
  },
  {
    id: "broome-st",
    name: "Broome Street Residential College",
    building: "Broome Street Residential",
    floor: "5th Floor Lounge",
    printer_type: "B&W Laser",
    latitude: 40.7208939,
    longitude: -73.997345,
    status: "unknown",
    last_updated: hoursAgo(90),
  },
  {
    id: "carlyle",
    name: "NYU Carlyle Court",
    building: "Carlyle Court",
    floor: "C1 Lounge",
    printer_type: "B&W Laser",
    latitude: 40.7362921,
    longitude: -73.9910827,
    status: "not_working",
    last_updated: hoursAgo(8),
    last_reported_by: "student",
  },
  {
    id: "coral-tower",
    name: "Coral Tower",
    building: "Coral Tower",
    floor: "Basement",
    printer_type: "B&W Laser",
    latitude: 40.7333752,
    longitude: -73.9867448,
    status: "unknown",
    last_updated: hoursAgo(55),
  },
  {
    id: "founders",
    name: "Founders Hall",
    building: "Founders Hall",
    floor: "Lobby",
    printer_type: "B&W Laser",
    latitude: 40.7320963,
    longitude: -73.9892506,
    status: "working",
    last_updated: hoursAgo(6),
  },
  {
    id: "goddard",
    name: "Goddard Hall",
    building: "Goddard Hall",
    floor: "Chaplin Lounge",
    printer_type: "B&W Laser",
    latitude: 40.7295878,
    longitude: -73.9962278,
    status: "unknown",
    last_updated: hoursAgo(100),
  },
  {
    id: "gramercy",
    name: "Gramercy Green",
    building: "Gramercy Green",
    floor: "1st Floor Lobby",
    printer_type: "B&W Laser",
    latitude: 40.7393473,
    longitude: -73.9830017,
    status: "unknown",
    last_updated: hoursAgo(112),
  },
  {
    id: "40e7th",
    name: "40 E 7th St",
    building: "40 E 7th Street",
    floor: "Basement Lounge",
    printer_type: "B&W Laser",
    latitude: 40.7281308,
    longitude: -73.9889792,
    status: "unknown",
    last_updated: hoursAgo(70),
  },
  {
    id: "greenwich",
    name: "Greenwich Hotel Residence Hall",
    building: "Greenwich Hotel Residence",
    floor: "1st Floor Lobby",
    printer_type: "B&W Laser",
    latitude: 40.731311,
    longitude: -74.00822,
    status: "unknown",
    last_updated: hoursAgo(85),
  },
  {
    id: "lipton",
    name: "Lipton Residence Hall",
    building: "Lipton Hall",
    floor: "Lobby",
    printer_type: "B&W Laser",
    latitude: 40.7314838,
    longitude: -73.9993363,
    status: "unknown",
    last_updated: hoursAgo(50),
  },
  {
    id: "palladium",
    name: "Palladium Residence Hall",
    building: "Palladium Hall",
    floor: "3rd Floor Lounge",
    printer_type: "B&W Laser",
    latitude: 40.7333658,
    longitude: -73.9882943,
    status: "working",
    last_updated: hoursAgo(7),
    last_reported_by: "student",
  },
  {
    id: "paulson-rc",
    name: "Residential College at Paulson",
    building: "370 Jay Street",
    floor: "7th Floor Lounge",
    printer_type: "B&W Laser",
    latitude: 40.7268084,
    longitude: -73.9970947,
    status: "unknown",
    last_updated: hoursAgo(65),
  },
  {
    id: "university-hall",
    name: "University Hall Residence Hall",
    building: "University Hall",
    floor: "1st Floor Lobby",
    printer_type: "B&W Laser",
    latitude: 40.7334396,
    longitude: -73.9891177,
    status: "unknown",
    last_updated: hoursAgo(78),
  },
  {
    id: "wsv2",
    name: "Washington Square Village #2",
    building: "Washington Square Village",
    floor: "1st Floor Lounge",
    printer_type: "B&W Laser",
    latitude: 40.7281645,
    longitude: -73.9972526,
    status: "unknown",
    last_updated: hoursAgo(88),
  },
  {
    id: "weinstein",
    name: "Weinstein Residence Hall",
    building: "Weinstein Hall",
    floor: "1st Floor Lobby",
    printer_type: "B&W Laser",
    latitude: 40.731052,
    longitude: -73.9950662,
    status: "not_working",
    last_updated: hoursAgo(10),
    last_reported_by: "student",
  },
  {
    id: "forbes",
    name: "Forbes Building",
    building: "Forbes Building",
    floor: "Basement",
    printer_type: "B&W Laser",
    latitude: 40.7350141,
    longitude: -73.9945785,
    status: "unknown",
    last_updated: hoursAgo(95),
  },
  {
    id: "sps-midtown",
    name: "SPS Midtown Center",
    building: "SPS Midtown",
    floor: "10th Floor",
    printer_type: "B&W Laser",
    latitude: 40.7543352,
    longitude: -73.981948,
    status: "unknown",
    last_updated: hoursAgo(105),
  },
  {
    id: "tisch",
    name: "Tisch School of the Arts",
    building: "Tisch School",
    floor: "7th Floor",
    printer_type: "Color Laser",
    latitude: 40.7294596,
    longitude: -73.9939123,
    status: "working",
    last_updated: hoursAgo(1.5),
    last_reported_by: "student",
  },
  {
    id: "woolworth",
    name: "Woolworth Building",
    building: "Woolworth Building",
    floor: "2nd Floor",
    printer_type: "B&W Laser",
    latitude: 40.7124389,
    longitude: -74.0085371,
    status: "unknown",
    last_updated: hoursAgo(115),
  },
  {
    id: "dibner",
    name: "Dibner Library",
    building: "5 MetroTech Center",
    floor: "3rd Floor",
    printer_type: "Color Laser",
    latitude: 40.6945396,
    longitude: -73.9856759,
    status: "working",
    last_updated: hoursAgo(0.5),
    last_reported_by: "student",
  },
  {
    id: "2-metrotech",
    name: "2 MetroTech Center",
    building: "2 MetroTech Center",
    floor: "Lobby (security desk)",
    printer_type: "Color Laser",
    latitude: 40.6934688,
    longitude: -73.9858783,
    status: "working",
    last_updated: hoursAgo(3),
    last_reported_by: "admin",
  },
  {
    id: "makergarage",
    name: "MakerGarage",
    building: "MakerGarage",
    floor: "2nd Floor (Lab-Card Access)",
    printer_type: "Color Laser",
    latitude: 40.6946118,
    longitude: -73.9829595,
    status: "unknown",
    last_updated: hoursAgo(52),
  },
  {
    id: "othmer",
    name: "Othmer Hall Residence Hall",
    building: "Othmer Hall",
    floor: "Common Area",
    printer_type: "B&W Laser",
    latitude: 40.6949576,
    longitude: -73.9869882,
    status: "unknown",
    last_updated: hoursAgo(68),
  },
  {
    id: "rogers",
    name: "Rogers Hall Residence Hall",
    building: "Rogers Hall",
    floor: "7th Floor Lab",
    printer_type: "B&W Laser",
    latitude: 40.6942089,
    longitude: -73.9867001,
    status: "working",
    last_updated: hoursAgo(4),
    last_reported_by: "student",
  },
  {
    id: "vanderbilt",
    name: "Vanderbilt Hall (NYU Law)",
    building: "40 Washington Square S",
    floor: "Multiple Floors",
    printer_type: "Color Laser",
    latitude: 40.7305635,
    longitude: -73.9995861,
    status: "unknown",
    last_updated: hoursAgo(58),
  },
];
